### ISSUE TITLE
RFC: Split packages for Ceph

### ISSUE THREAD

**Issue by bazaah** [bazaah/aur-ceph#15]
This is a request for community feedback on my planned splitting of Ceph into smaller component packages.

The jist of these changes are:

1. Breaking up the build into libs and binary packages
2. Clearly defining the in-package dependencies
3. Substantial reduction in runtime dependencies for most users
4. Ability to just install the bits relevant to your system, notably the `ceph` CLI utility
5. Improved `.so` provides()
6. Ease of package maintence

See the diagrams for a visual representation, or visit the [PKGBUILD](https://github.com/bazaah/aur-ceph/blob/experimental/v17.2.6/PKGBUILD#L563) for the code.

### Old

<details>
<summary>Details</summary>

The current dep tree:

```mermaid
graph TD

	mgr{{ceph-mgr}} ---> ceph{{ceph}} ---> libs{{ceph-libs}};
```

</details>

### New

<details>
<summary>Show</summary>

My proposed package dep tree:

```mermaid
graph TD
    subgraph CORE
        direction BT

        subgraph COMMON
            direction LR

            ceph-common[[ceph-common]];
            ceph-compressor[[ceph-compressor]];
            ceph-crypto[[ceph-crypto]];
            ceph-erasure[[ceph-erasure]];
        end

        subgraph RADOS
            direction LR

            librados[[librados]];
			ceph-rados[[ceph-rados]];
        end

		libcephsqlite[[libcephsqlite]];
    end

    subgraph CLUSTER
        direction TB

		ceph-base{{ceph-base}};
        ceph-mon{{ceph-mon}};
        ceph-osd{{ceph-osd}};
		ceph-mds{{ceph-mds}};
		ceph-mgr{{ceph-mgr}};
		ceph-rgw{{ceph-rgw}};
    end

    subgraph APPS
        direction TB

        subgraph RBD
            direction LR

			librbd[[librbd]];
            ceph-rbd{{ceph-rbd}};
			ceph-volume{{ceph-volume}};
        end

        subgraph FS
            direction LR

			libcephfs[[libcephfs]];
			ceph-cephfs{{ceph-cephfs}};
			cephfs-shell{{cephfs-shell}};
			cephfs-top{{cephfs-top}};
            java-cephfs[/java-cephfs\];
        end

        subgraph RGW
            direction LR

            librgw[[librgw]];
        end
    end

	subgraph MISC
		direction TB

		cephadm{{cephadm}};
		ceph-tools{{ceph-tools}};
		ceph-test{{ceph-test}};
	end

	subgraph PYTHON
		direction TB

		py-ceph-common[[python-ceph-common]];
		py-rados[[python-rados]];
		py-rgw[[python-rgw]];
		py-rbd[[python-rbd]];
		py-cephfs[[python-cephfs]];
	end

	subgraph VIRTUAL
		direction TB

		ceph-libs((ceph-libs));
		ceph-cluster((ceph-cluster));
		ceph-util((ceph-util));
		ceph((ceph));
	end

    %% COMMON
    ceph-common --> ceph-compressor;
    ceph-common --> ceph-crypto;
    ceph-common --> ceph-erasure;

    %% RADOS
    librados --> ceph-common;
	ceph-rados --> librados;

	%% SQLITE
	libcephsqlite ---> librados;

    %% CLUSTER
	ceph-base ---> ceph-common & librados & py-ceph-common;
    ceph-mon --> ceph-base;
    ceph-osd --> ceph-base;
    ceph-mds --> ceph-base;
	ceph-rgw --> ceph-base & librgw;
    ceph-mgr --> ceph-base; ceph-mgr ---> py-cephfs & py-rbd & libcephsqlite;

    %% RBD
    librbd ----> librados;
	ceph-rbd --> librbd;

    %% FS
    libcephfs ----> librados;
	ceph-cephfs --> libcephfs;
	java-cephfs ---> libcephfs;
	cephfs-shell ---> py-ceph-common & py-cephfs;
	cephfs-top ---> py-ceph-common & py-cephfs;

    %% RGW
    librgw ----> librados;

	%% MISC
	ceph-tools ----> ceph-base;
	ceph-test ----> ceph-base;
	ceph-volume ---> ceph-osd & py-ceph-common;

	%% Python
	py-ceph-common ----> ceph-common;
	py-rados --> py-ceph-common ; py-rados ----> librados;
	py-rbd --> py-ceph-common & py-rados; py-rbd ----> librbd;
	py-cephfs --> py-ceph-common & py-rados; py-cephfs ----> libcephfs;
	py-rgw --> py-ceph-common & py-rados; py-rgw ----> librgw;

	%% VIRTUAL
	ceph-libs ----> librados & librbd & libcephfs & librgw & libcephsqlite;
	ceph-cluster ----> ceph-mon & ceph-mgr & ceph-osd & ceph-mds & ceph-rgw & ceph-volume;
	ceph ----> ALL;
```

</details>

## What

This is a large (mostly) backwards compatible modification to the way Ceph is packaged for Archlinux, bringing it more inline with how Debian and RHEL packages work.

We split the existing _ceph_ and _ceph-libs_ package monoliths into much smaller, well defined packages along the following themes:

#### Core

This is primarily the common, shared code between internal components, the ceph config libs and most externally: ceph-rados and librados, which form the base clients that all ceph applications use to communicate with the cluster.

#### Cluster

The server side components. Namely the monitor, manager, osd, (cephfs) metadata, and rados gateway daemons; these form the backend or server side of a ceph cluster.

#### Clients and applications

These are the various clients both against rados directly and against ceph applications like RBD, CephFS and RGW.

#### Python

The various python bindings exposed by Ceph, often these are dual purpose, both utilized by, and for exposing Ceph cluster and application APIs.

#### Misc.

Various bits that aren't strongly tied to anything else, some examples include the java cephfs JNI bindings, utilities for benchmarking clusters and misc. CLI tooling of limited value

#### Virtual

These are "targets" and are used purely for the side effects of installing dependencies, to meet some understandable operator goal, for example _"all ceph sonames"_ or _"all cluster components"_.

## Why

There are two primary umbrellas for this change:

### UX

As a user of the Ceph packages it frustrates me to no end that I have to pull in an entire JVM dep tree for a set of JNI bindings that likely, no one uses.
In the same spirit, it is irritating that I need ~200M of unrelated binaries to simply have access to the `ceph` CLI utility on a machine.

Both of these issues are fixed.

From a downstream packagers perspective, it also greatly improves the situation as we no longer need ~30M of unrelated binaries for the one soname we care about in our build(), and each package now correctly notes the `.so`s it provides, meaning we get to play nicely with libalpm's soname resolution

### Maintainability

From the packagers perspective, the changes have made it much easier to correctly package Ceph, both in the refactoring around `_make_ceph_packages()` _and_ in having a clear understanding of what goes where.

## When

My plan is to make these changes public (e.x: pushed to AUR) as a part of the ceph v18 release, which will likely happen in July (~2 months from date of posting this); assuming I haven't received a compelling reason to _not_ do this.

----

### Source builds

That is, users of: https://aur.archlinux.org/pkgbase/ceph

I'm hopeful that this change is relatively opaque to casual users of the package, and I don't think I'll even need to raise the epoch for this, as the virtual packages _should_ make this nothing more than an update with ~30 more ceph packages than usual.

### Binary packages

That is, users of: https://aur.archlinux.org/pkgbase/ceph-bin

I'm uncertain if I will propagate these changes to the binary packages, as I feel this will pollute the aur namespace with `-bin` suffixed packages.

I'm interested in feedback on whether **hosting a third-party repository with the binary packages** would be interesting to users. If so, I can make public my internal ceph repo.

Regardless, likely users of the AUR packages _will not experience any change_, and I'll transparently remerge the split packages into the `ceph{,-libs,-mgr}-bin` packages that currently exist.

----

### Leave feedback

I'm inetrested in hearing what the community has to say about this change. The most useful thing you can do is leave a thoughtful comment below about these changes. Or if that's to much work a :+1: or :-1: on this issue would be great.

### Test it out

I have created a public Archlinux repo with v17.2.6-2 artifacts split into the new package scheme, and would appreciate any feedback on them, if you feel inclined to try them out.

_That said_, these **have not been tested**, beyond the usual unit tests in `check()` that Ceph provides, and I reserve the right to wipe them whenever I please, so **do not use them for anything you care about**, they are for _testing only_.

1. Grab and trust the signing key

```bash
pacman-key --recv-key AA2F58D04E59C080 --keyserver keyserver.ubuntu.com
pacman-key --lsign-key AA2F58D04E59C080
```

2. Install the keyring

```bash
pacman -U https://storage.st8l.com/archlinux/repo/ceph-test/os/x86_64/st8l-keyring-1.0.0-1-any.pkg.tar.zst
```

3. Add the repo to your `pacman.conf`

```conf
# /etc/pacman.conf
[ceph-test]
Server=https://storage.st8l.com/archlinux/repo/$repo/os/$arch
```

4. Query the repo

```bash
pacman -Syy && pacman -Ss ceph-
```

**Comment by nicolamori** [comment]
Hi, I'm generally in favor of this especially if it helps you in maintaining the whole thing. I just use the ceph packages for the CLI utility so my testing possibilities are limited, but I'll try to give you a feedback as soon as possible.
Thank you for your work!

**Comment by mp-bgp** [comment]
Would love to see this. I'm was building ceph on multiple systems, only because I needed mount.ceph. Having the client parts of ceph in a seperate package, means I could remove a lot of fiddly workarounds. This does me a solid, thanks mate.
